### ISSUE TITLE
Quick setting Tile not updating property, sometimes theres a huge delay

### ISSUE THREAD

**Issue by fedonr** [abdalmoniem/Caffeinate#48]
With Android 14 and higher, it seems to be the issue. So Quick setting tile does correctly start and stop caffeinate but the state of showing it ON or Off in Quick Tile doesn't update in the Tile itself.

**Comment by Niavy64** [comment]
On my Pixel 6 Pro it worked well on Android 14, but not on Android 15. Quick settings tile behaviour is totally different : one click toggles 5:00, second click PAUSES apparently countdown instead of stepping up. It appears that in reality, QS tile gets countdown OFF while showing a countdown freeze.

**Comment by abdalmoniem** [comment]
it appears that some device models (like samsung) don't respond to the quick tile update requests sent by the application, this issue also appears on the new Android 15 version.

I have created a workaround in the commit https://github.com/abdalmoniem/Caffeinate/commit/260414b238abc9c4def242cbc81939b263265555 ([tag v1.7.0](https://github.com/abdalmoniem/Caffeinate/tree/v1.7.0)), check release [v1.7.0](https://github.com/abdalmoniem/Caffeinate/releases/tag/v1.7.0) and tell me if the issue still persists.

**Comment by fedonr** [comment]
Awesome it works as expected, issue seems resolved. Thanks a lot , closing the issue.
