### ISSUE TITLE
Reproducible Builds broken with v2.0.0

### ISSUE THREAD

**Issue by IzzySoft** [abdalmoniem/Caffeinate#71]
Starting with v2.0.0, Caffeinate is no longer reproducible as you [insert build-time](https://github.com/abdalmoniem/Caffeinate/blob/main/app/build.gradle.kts#L40)  into the APK, which is non-deterministic. Could you please revert that change? As apart from that, it rebuilds fine – at least since v1.4.5 when it was added to my builder.

For some background, please see: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients) (and also our  [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for developers).

Thanks in advance!

**Comment by IzzySoft** [comment]
PS, while I'm here: today's updater run reported

    ! repo/com.hifnawy.caffeinate_31.apk declares sensitive permission(s): android.permission.SYSTEM_ALERT_WINDOW

Could you please clarify what that is needed/used for?

**Comment by abdalmoniem** [comment]
I will look into the build time issue, I'm using it to differentiate between builds during development stages, since the `versionCode` and `versionName` don't change between one dev./debug version and the other. maybe I should add this build configuration field only for debug variants (I don't know if that'll still cause an issue or not)

the `android.permission.SYSTEM_ALERT_WINDOW` permission is required to show an overlay window, this was suggested in issue #51 to fix the restrictions that some OEMs put on running foreground services for extended periods of time (the whole idea of this project 😅) it can be toggled on/off from the application settings.

**Comment by IzzySoft** [comment]
> I should add this build configuration field only for debug variants (I don't know if that'll still cause an issue or not)

That should work, yes. Alternatively, you could also use commit information (you'll probably not make development builds from tags, and neither release builds from "untagged" commits – and commit information should be deterministic (unless you rewrite git history, which you'd better not) – something like `GIT_COMMIT_COUNT="$(($(git rev-list --all --count) -1))"` (taken from another project)).

> `android.permission.SYSTEM_ALERT_WINDOW`

Thanks! Added to your app's "green list":

```yaml
android.permission.SYSTEM_ALERT_WINDOW: needed to keep a prolonged WAKE_LOCK using an overlay window
```

**Comment by abdalmoniem** [comment]
fixed build date issue in https://github.com/abdalmoniem/Caffeinate/commit/24cc91e2107605b4335b581a4b79196bcfbdb005 ([tag v2.0.1](https://github.com/abdalmoniem/Caffeinate/tree/v2.0.1)), please check release [v2.0.1](https://github.com/abdalmoniem/Caffeinate/releases/tag/v2.0.1)

**Comment by IzzySoft** [comment]
Confirmed, builds fine again now as RB without manual intervention, thanks!
